### PR TITLE
Allow for WebVTT cue identifers

### PR DESCRIPTION
**Pull request by sampattuzzi**
This is allowed in the standard here:
https://www.w3.org/TR/webvtt1/#introduction-other-features

### CODE REVIEW

**Comment by glut23** [comment]
Hi @sampattuzzi I have the webvtt parser refactored that supports cue identifiers, comments and other features. I refactored the parser to be easier to parse the caption blocks. It is still a work in progress but I will push it to the repo if you want to have a look and implement some missing feature in that branch. Thanks a lot for your contributions on the project.

**Comment by sampattuzzi** [comment]
That would be great. Let me know what needs doing to it and I will happily take a look.

**Comment by glut23** [comment]
Hi @sampattuzzi that work I mentioned is in webvtt_refactor branch. One thing I had in mind adding is implementing cue settings:
https://www.w3.org/TR/webvtt1/#cue-settings
If you want to take a look at this or any other missing feature that you find in the specs that would be great. Thanks for your help!

**Comment by glut23** [comment]
Hi @sampattuzzi the recent release v0.4.0 handles cue identifiers so I am closing this pull request. Thanks for your work.

**Pull request closed without merging**
